### PR TITLE
Updating orange hex

### PR DESCRIPTION
**Pull request by jennank**
## Purpose
The goal of this PR is to resolve issue #14, replacing the current orange with `#ff7f0e`.

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
N / A

## Checklist
- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by jennank** [comment]
I see the tests fail, these aren't lines I changed but I can run the formatter and update them for this PR.

**Comment by A-CGray** [comment]
Hey Jenna, thanks for pointing this out, I'd never noticed. I like the new orange but it is now a little close to the yellow/gold colour, although definitely not as close as the previous version was to red (see below). Can we tweak the orange ever so slightly so that it's a bit more distinct?

I would like to keep the old orange as I think it's a nice colour, but I'll rename it `RedOrange` and also remove it from the colour cycle

Screenshot from 2022-01-29 18-51-44

**Comment by jennank** [comment]
I was unable to reproduce the errors locally, but changed the files based on the GH log. This now directly conflicts with local black, but should pass the checks on GH.

**Comment by jennank** [comment]
It is similar, you're right. We could try making the orange lighter, such as `#ff8f00`, or changing the yellow to something like `#FFD700` to make it more yellow, and less golden.

**Comment by A-CGray** [comment]
Ugh, I dunno what's happening with the formatting, will fix tomorrow

**Comment by nwu63** [comment]
Unlike the checks in Azure, the YAML file doesn't specify the version of `black`. Incidentally, they just released a new version(no longer in beta) that made some changes to the format output. I suggest that we pin the version until the entire mdolab organization is ready to move to the new format. As a side note, they have now promised to do this only once a year in the first release, so it should be more stable going forward.

**Review by A-CGray — APPROVED** [review]

**Pull request merged**
