### PR TITLE
Updated draggable legend kwargs

### PR DESCRIPTION
**Pull request by marcomangano**
## Purpose

Quick PR to add a few more `kwargs` to the `draggable_legend` function

## Expected time until merged

Very short, 2 days?

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by A-CGray** [comment]
Why not just add `**kwargs` to the draggable legend function and then pass those to annotate, that way `draggable_legend` will automatically support all of the possible inputs to `annotate`

**Comment by marcomangano** [comment]
oh yeah that makes more sense, nice

**Comment by A-CGray** [comment]
@marcomangano can you check that this version works for whatever case you were testing on?

**Review by A-CGray — APPROVED** [review]

**Comment by marcomangano** [comment]
> @marcomangano can you check that this version works for whatever case you were testing on?

Yeah, it's working fine. Thanks!

**Pull request merged**
