### PR TITLE
Added docs

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose

I added docs using the [sphinx-gallery](https://github.com/sphinx-gallery/sphinx-gallery) extension to show an example gallery. Through that, the figures are auto-generated at build time and displayed, so we do not need to keep the png and pdfs.

TODO:
- [x] add autodocs
- [ ] expand docstrings
- [ ] tweak sphinx-gallery configurations

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
Would be good to get some initial feedback on this before I change the other stuff I think

**Comment by A-CGray** [comment]
Is there any way we can alter the environment that sphinx runs the examples in?

In the optimisation problem example, it's not using a version of matplotlib recent enough to be able to do the hashed constrain boundaries, so both the output images look the same:

Screenshot_20220324_153337

And in one of the other examples we're getting the warning that the cmbright font is not available:

Screenshot_20220324_153521

**Comment by nwu63** [comment]
I updated matplotlib and installed the CMU fonts to RTD.

**Comment by nwu63** [comment]
So, in terms of remaining TODOs, I think ideally we do the following:
- fix some docstrings (e.g. math rendering etc.) and sphinx linking to other functions
- add a bit more text to explain the examples, or make them more uniform
- move some of the installation notes from the README to the RST files

I probably won't be touching this PR much beyond what is there currently, so unless someone volunteers for those, I'm okay with merging this.

**Review by A-CGray — APPROVED** [review]

**Pull request merged**
