### PR TITLE
Update testing matrix, start using image comparison

### PR DESCRIPTION
**Pull request by A-CGray**
## Purpose

Update the versions of python, numpy and matplotlib we test against, now using python 3.9/10/11. For numpy and matplotlib I'm using both the latest release and the oldest supported release as listed [here](https://scientific-python.org/specs/spec-0000/). This reduces the total number of CI jobs as we used to test against 3 versions of numpy.

Secondly, I was finally able to implement some parsing so that the image comparison checks I added in #30 only fail if the number of pixels that differ between images is > 0.05%, this should mean the test will only fail when there are actual meaningful differences between the images.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by eytanadler** [comment]
Is there any world in which the reference images could be generated slightly differently on different operating systems or Python environment setups and cause these tests to fail? If I remember correctly, there have been cases when I've used matplotlib and gotten different results on different computers.

**Comment by A-CGray** [comment]
> Is there any world in which the reference images could be generated slightly differently on different operating systems or Python environment setups and cause these tests to fail? If I remember correctly, there have been cases when I've used matplotlib and gotten different results on different computers.

Yeah, that's what the tolerance on the allowable fraction of different pixels is meant to handle.

**Review by eytanadler — COMMENTED** [review]
Ok, looks good to me then! My only request is to undo bumping the patch, because no lines in the source code have actually changed (the PyPI code will be identical).

**Comment by A-CGray** [comment]
> Ok, looks good to me then! My only request is to undo bumping the patch, because no lines in the source code have actually changed (the PyPI code will be identical).

I was bumping the version due to the changes in #39 , but I can put that in a separate PR if you want

**Review by eytanadler — APPROVED** [review]
Oh ok, I didn't realize

**Pull request merged**
